### ISSUE TITLE
Remove bedrock-identity peer dependency

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-account#11]
Remove `manageIdentity` API and bedrock-identity dependency, that module is deprecated.

**Comment by dlongley** [comment]
Support for callbackified functions should also be removed when this happens as it will be a breaking change moving to a new major version.

**Comment by aljones15** [comment]
Please note that:

```js
const validateCapabilityDelegation = promisify(brIdentity.validateCapabilityDelegation);
```

this in turn is used in almost every function.

**Comment by dlongley** [comment]
I think `validateCapabilityDelegation` is only used in `account.insert` and we can just remove it there. Callers of the `account.insert` API are responsible for ensuring the roles being set are permitted.
