### ISSUE TITLE
Log always says "inserting account" even if account insert fails ... address somehow

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-account#3]

**Comment by mattcollier** [comment]
This pertains to this line: https://github.com/digitalbazaar/bedrock-account/blob/master/lib/index.js#L164

Which logs in advance of an effort to actually insert the account.

@dlongley would changing the language to 'attempting to insert account' be adequate?

**Comment by dlongley** [comment]
> would changing the language to 'attempting to insert account' be adequate?

Yes.
