### ISSUE TITLE
Invalid sequence on update does not throw an error

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-account#7]
This might be intentional, but I might have found a bug:

```js
  if(record.meta.sequence !== sequence) {
    return new BedrockError(
      'Could not update Account. Record sequence does not match.',
      'InvalidStateError', {
        httpStatusCode: 409,
        public: true,
        actual: sequence,
        expected: record.meta.sequence
      });
  }

  const errors = jsonpatch.validate(patch, record.account);
  if(errors) {
    throw new BedrockError(
      'The given JSON patch is invalid.', 'ValidationError', {
        httpStatusCode: 400,
        public: true,
        patch,
        errors
      });
  }
```
in the meta sequence we return a new BedRockError object
in the other case we throw.
the inconsistently means that when the passed in sequence does not match the 
sequence from the database it returns an error object.

So which behavior do we want returning an object or throwing an error?

**Comment by aljones15** [comment]
oh yeah one more thing: update only let's you update record.account which is the DID or the email assigned to the account. if we are going to support toggling status we will need to change the updater to work on the entire record.

**Comment by aljones15** [comment]
also no try catch is currently receiving the error from the database update.

**Comment by aljones15** [comment]
also no check which means you can overwrite the id easily

**Comment by dlongley** [comment]
It's a typo, it should be throwing. And clearly, we need a better test for that. :)

**Comment by dlongley** [comment]
> if we are going to support toggling status we will need to change the updater to work on the entire record.

The low-level APIs split up updating status and roles from patching the account info. We'll want the update endpoint to handle calling the appropriate API based on what is sent in/what the URL query is.

**Comment by aljones15** [comment]
add me to this repo will change and add it the test in next pomodoro. just finished the patch ability with bedrock-account-http

**Comment by aljones15** [comment]
> > if we are going to support toggling status we will need to change the updater to work on the entire record.
> 
> The low-level APIs split up updating status and roles from patching the account info. We'll want the update endpoint to handle calling the appropriate API based on what is sent in/what the URL query is.

ok cool will look into it. I did see tests for that in bedrock-account

**Comment by dlongley** [comment]
> also no check which means you can overwrite the id easily

Yeah, I can't remember where we were going to handle that, but it does need to be handled.

**Comment by aljones15** [comment]
hmmm so has that decission been made or should I add a test for mismatched ids and make sure it throws as it should?

**Comment by aljones15** [comment]
also I guess I should throw in a linter while I'm at it.

**Comment by dlongley** [comment]
> hmmm so has that decission been made or should I add a test for mismatched ids and make sure it throws as it should?

You can throw in a check for mismatched IDs. My guess is that the validator was supposed to catch that in the patch ... and if we find that we need to check a bunch of other stuff, it will become more clear that a validator is the way to go rather than a bunch of specific `if` statements in the code.

**Comment by aljones15** [comment]
actually you can remove the 0 < check once the bedrock-account-http changes are merged.
the validator does check to make sure the sequence is 0 or greater. no negatives allowed.

**Comment by aljones15** [comment]
ok covered this in the PR.

**Comment by aljones15** [comment]
@mattcollier it now throws and in the release so closing this.

https://github.com/digitalbazaar/bedrock-account/blob/ac890f9dc9184a28946aada13f845df1424bf6b1/lib/index.js#L324
